steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-f','Dockerfile.kis_pipeline','-t','asia-northeast3-docker.pkg.dev/model-osprey-487403-h2/cloud-run-source-deploy/kis-pipeline-job:20260304-052658','.']
images:
- 'asia-northeast3-docker.pkg.dev/model-osprey-487403-h2/cloud-run-source-deploy/kis-pipeline-job:20260304-052658'
